# Playbook to host a static website on webserver nodes
---
- name: host static website on webserver nodes
  hosts: webserver
  tasks:
    - name: Install nginx on webserver nodes
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
  
    - name: copy html file to managed nodes
      ansible.builtin.copy:
        src: /home/ubuntu/.ansible/Web_Development/index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
  
    - name: copy css file to managed nodes
      ansible.builtin.copy:
        src: /home/ubuntu/.ansible/Web_Development/sai.css
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
  
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started



# Playbook to install Jenkins on dev_node
- name: install jenkins on dev_node
  hosts: dev_node
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java for Jenkins
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository to sources list
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
